apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
  labels:
    app: chromium
  name: chromium
spec:
  selector:
    matchLabels:
      app: chromium
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: chromium
    spec:
      hostNetwork: true
      containers:
      - name: chromium
        image: jaredallard/chromium-rpi:v1.0.0
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
        env:
        - name: KIOSK_URL
          valueFrom:
            configMapRef:
              name: kiosk
              key: url
              optional: true
        volumeMounts:
        - name: xauth
          mountPath: /mnt/xauth
      - name: xorg
        image: jaredallard/xorg-rpi:v1.0.0
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
          runAsNonRoot: false
          privileged: true
        volumeMounts:
        - name: xauth
          mountPath: /mnt/xauth
      volumes:
      - name: xauth
        emptyDir: {}